Repository cryptic-game/frontend, pull requests merged in 2020-05, with the labels that each got.

#150 Removed browser desktop icon
  src/assets/desktop/definition.ts
Labels: enhancement

#151 Added description to the commands displayed with the help command
  src/app/desktop/windows/terminal/terminal-states.ts
Labels: enhancement

#153 Fixed HardwareShop
  src/app/desktop/windows/hardware-shop/hardware-shop.service.ts
Labels: bug

#159 Updated Signup to new backend
  src/app/account/account-page-base/account-page-base.component.ts
  src/app/account/account.service.spec.ts
  src/app/account/account.service.ts
  src/app/account/login/login.component.html
  src/app/account/sign-up/sign-up.component.html
  src/app/account/sign-up/sign-up.component.spec.ts
  src/app/account/sign-up/sign-up.component.ts
Labels: backend
