Repository cryptic-game/frontend, pull requests merged in 2020-08, with the labels that each got.

#168 Desktop icons
  src/app/desktop/desktop-menu/desktop-menu.component.scss
  src/assets/desktop/img/filemanager.svg
  src/assets/desktop/img/gear.svg
  src/assets/desktop/img/hardware-shop.svg
  src/assets/desktop/img/hardware_shop_app.svg
  src/assets/desktop/img/morphcoin_dark.svg
  src/assets/desktop/img/task-manager.svg
  src/assets/desktop/img/terminal.svg
  src/assets/desktop/img/wallet_app.svg
Labels: design

#177 Disables the resizing of windows that are minimized
  src/app/desktop/window/window-frame.component.ts
Labels: bug

#171 added maxlength check for username in sign-up
  src/app/account/sign-up/sign-up.component.html
  src/app/account/sign-up/sign-up.component.ts
Labels: bug

#179 Changed the mc display from seconds to hours
  src/app/desktop/windows/miner/miner.component.html
Labels: enhancement
